# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage settings
coverage:
  precision: 2
  round: down
  range: 60..100
  
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

# Only track files in the /core directory
ignore:
  - "tools/**/*"
  - "external/**/*"
  - "target/**/*"
  - "tests/**/*"
  - "book/**/*"
  - "**/test_data/**/*"
  - "**/tests/**/*"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.toml"
  - "**/*.json"

# Specify paths to track
fixes:
  - "core/::"

# Comment settings for pull requests
comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Component configuration - track each core crate separately
component_management:
  individual_components:
    - component_id: ast
      name: "AST"
      paths:
        - core/ast/**
    
    - component_id: cli
      name: "CLI"
      paths:
        - core/cli/**
    
    - component_id: inference
      name: "Inference Core"
      paths:
        - core/inference/**
    
    - component_id: wasm-codegen
      name: "WASM Codegen"
      paths:
        - core/wasm-codegen/**
    
    - component_id: wasm-to-v
      name: "WASM to V Translator"
      paths:
        - core/wasm-to-v/**

# Flag management for better organization
flag_management:
  default_rules:
    carryforward: true
    
# GitHub checks
github_checks:
  annotations: true
